
SRC := $(wildcard *.c)
OBJ := $(SRC:.c=.o)
EXC := $(SRC:%.c=%)

CFLAGS := -g

all : $(EXC)
# all: ex1 ex2

# ex1: ex1.o

# ex1.o: ex1.c

# ex2: ex2.o

# ex2.o: ex2.c

# % : $(OBJ)

clean:
	rm -rf *.o $(EXC)